---
- name: Creating keycloak user group
  group:
    name: "{{ keycloak_group }}"
  become: true

- name: Creating vault user
  user:
    name: "{{ keycloak_user }}"
    group: "{{ keycloak_group }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "keycloak nologin user"
    createhome: "no"
    state: present

- name: Download keycloak zip file
  ansible.builtin.get_url:
    url: "https://github.com/keycloak/keycloak/releases/download/{{ keycloak_release }}/keycloak-{{ keycloak_release }}.zip"
    dest: /tmp/keycloak.zip

- name: Unzip keycloak archive
  ansible.builtin.unarchive:
    src: /tmp/keycloak.zip
    dest: /opt
    remote_src: yes

- name: Rename keycloak directory to canonized version
  command:
    cmd: "mv /opt/keycloak-{{ keycloak_release }} /opt/keycloak"
    creates: /opt/keycloak

- name: Copy certificate into keycloak directory
  copy:
    src: /home/ubuntu/samba.pem
    dest: /opt/keycloak/conf/server.crt.pem
    remote_src: yes

- name: Copy key into keycloak directory
  copy:
    src: /home/ubuntu/key.pem
    dest: /opt/keycloak/conf/server.key.pem
    remote_src: yes

