---
krb5_config:
  - insertafter: '.*dns_lookup_kdc = true'
    section: libdefaults
    block: |4
          default_tkt_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 arc-four-hmac rc4-hmac
          default_tgs_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 arc-four-hmac rc4-hmac
          permitted_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 arc-four-hmac rc4-hmac
  - insertafter: '.*default_domain = {{domain_name}}'
    section: realms
    block: |4
        kdc = {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}
        admin_server = {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}
