- name: Creating vault user group
  group: 
    name: "{{ vault_group }}"
  become: true

- name: Creating vault user
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "vault nologin User"
    createhome: "no"
    state: present

- name: Import Hashicorp apt key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: true

- name: Install Hashicorp Vault deb repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present
  become: true

- name: Install Hashicorp Vault
  apt:
    name: vault
    state: present
    update_cache: true
  become: true

- name: "Set vault binary capabilities"
  capabilities:
    path: /usr/bin/vault
    capability: cap_ipc_lock+ep
    state: present

- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
  notify: systemd_reload

- name: config file
  template:
    src: vault.hcl.j2
    dest: "{{ vault_config_path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: vault service
  service:
    name: vault
    state: started
    enabled: yes

- name: Install Java 11 (for keytool)
  apt:
    name: openjdk-11-jdk
    state: present

