---
- name: Install packages
  package:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - postgresql
    - postgresql-contrib
    - python3-psycopg2
    - acl # required to solve https://docs.ansible.com/ansible-core/2.14/playbook_guide/playbooks_privilege_escalation.html#resolving-temporary-file-error-messsages

- name: Start and enable PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Enable external access and logging in postgresql.conf
  lineinfile:
    path: /etc/postgresql/16/main/postgresql.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regexp: 'listen_addresses', line: "listen_addresses = '*'" }
  notify:
    - Restart PostgreSQL

- name: Enable access for keycloak user
  lineinfile:
    path: /etc/postgresql/16/main/pg_hba.conf
    regexp: "hostssl keycloak	keycloak	127.0.0.1/32		scram-sha-256"
    line: "hostssl keycloak	keycloak	127.0.0.1/32		scram-sha-256"
    insertafter: EOF
    state: present
  notify:
    - Restart PostgreSQL

- name: Create new database with name "keycloak"
  become: true
  become_method: su
  become_exe: sudo su -
  become_user: postgres
  postgresql_db:
    name: keycloak
    state: present

- name: Create 'keycloak' user
  become: true
  become_method: su
  become_exe: sudo su -
  become_user: postgres
  postgresql_user:
    db: keycloak
    name: "keycloak"
    password: "keycloakpass"
    priv: ALL

- name: Remove unnecessary permissions from 'keycloak'
  become: true
  become_method: su
  become_exe: sudo su -
  become_user: postgres
  postgresql_user:
    name: "keycloak"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present

- name: GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak
  become: true
  become_user: postgres
  community.postgresql.postgresql_privs:
        db: keycloak
        privs: ALL
        type: database
        user: keycloak

- name: ALTER DATABASE keycloak OWNER TO keycloak
  become: true
  become_user: postgres
  community.postgresql.postgresql_owner:
        db: keycloak
        new_owner: keycloak
        obj_type: database
