---
# Copy LDIF directory to target

- name: Ensure directories exists on target
  file:
    state: directory
    dest: "/home/ubuntu/{{ item.path }}"
    owner: ubuntu
    group: ubuntu
  with_filetree: "{{ role_path }}/files/"
  when: item.state == 'directory'

- name: Copy files to target and process templates
  template:
    src: '{{ item.src }}'
    dest: '/home/ubuntu/{{ item.path }}'
    owner: ubuntu
    group: ubuntu
  with_filetree: "{{ role_path }}/files/"
  when: (item.state == 'file') and ('html' not in item.src)

- name: Copy html files (not as template)
  copy:
    src: '{{ item.src }}'
    dest: '/home/ubuntu/{{ item.path }}'
    owner: ubuntu
    group: ubuntu
  with_filetree: "{{ role_path }}/files/"
  when: (item.state == 'file') and ('html' in item.src)

# ls -d returns the directory, with * the full path
- name: List files in remote directory
  shell: ls -d /home/ubuntu/ldifs/*
  register: ldif_files
  changed_when: false

- name: Add LDIFS
  shell: ldapadd -H ldaps://samba.{{domain_name}} -D Administrator@{{realm}}  -w Bootcamp4Ever -f "{{ item }}"
  register: ldapadd_result
  changed_when: ldapadd_result.rc == 0
  failed_when: ldapadd_result.rc != 0 and ldapadd_result.rc != 68
  with_items: "{{ ldif_files.stdout_lines }}"
